### ISSUE TITLE
upstream

### ISSUE THREAD

**Issue by loriab** [loriab/libxc#1]
Communicate with upstream Libxc people

- [ ] make sure they know about this hosting and are ok with public repo and [README.md](https://github.com/loriab/libxc/blob/master/README.md) as-is temporarily
- [ ] find out if they would rather we (Psi4) pulled a tarball and this repo hosted only the CMake wrappings. or if they're interested in CMake upstream at all.
- [ ] make sure they're ok with a conda package. @loriab has talking points, if required.
- [ ] find out what they consider to be the project name/capitalization. Currently using `Libxc`

**Comment by loriab** [comment]
@susilehtola

I think I saw one of your posts commenting about libxc and CMake once, so FYI.

**Comment by susilehtola** [comment]
@loriab oh cool. I'm sure CMake build files could go into libxc proper, if they came in a general form. I've suggested switching to CMake on the libxc-devel list before, but the main authors didn't really warm up to it since there's still lots of supercomputers which don't have CMake... but I'm pretty sure we could ship it as a supplementary build system.

**Comment by loriab** [comment]
@susilehtola, great! I'll let you all know when the build system is more field tested (libxc+Psi4 is less than a week old). Yes, the libtool build system looks like it's had some very careful tuning over the years that this CMake doesn't begin to emulate. I always `conda install cmake` wherever needed, but I certainly understand accommodating users' hardware. If you've opinions on the name/capitalization, if not `Libxc`, it'd be good to get that fixed early, since CMake is particular about its exported target names. Thanks for the correspondence.

**Comment by loriab** [comment]
cmake was added to upstream https://gitlab.com/libxc/libxc in the late libxc3 days.
